### ISSUE TITLE
Load binary simularium files locally or from URL

### ISSUE THREAD

**Issue by blairlyons** [simularium/simularium-viewer#123]
## Use Case

When a user is drag and dropping a local simularium file, or loading one from a URL, it would be nice to support the binary version of simularium file format as well as JSON, that way the files can be smaller, and download and/or load faster.

## Solution

- Binary simularium reading is already implemented for trajectories streaming from the backend, add support for the load local and load from URL code paths as well. 
- Also, add an endianess check since users could be generating their own binary outside of SimulariumIO.

## Acceptance Criteria

1. A simularium binary file can be drag/dropped on the view and loaded
2. A simularium binary file posted on a supported public cloud can be downloaded and loaded

## Dependencies

https://github.com/allen-cell-animated/simulariumio/issues/30 - SimulariumIO write binary Simularium files

**Comment by blairlyons** [comment]
@EricJIsaac here's a test binary file: https://aics-simularium-data.s3.us-east-2.amazonaws.com/trajectory/nanoparticle_wrapping_4_filtered_bin.simularium
This is the same data as the posted "Membrane Wrapping a Nanoparticle" example, except of course the binary format doesn't include the TrajectoryInfo block. lmk if anything is wrong with the file, I've only been able to test that the float values in the buffer are correct before writing to binary, since we don't yet have a way to visualize non-streaming binary in viewer.

**Comment by blairlyons** [comment]
for context, see the code I used to generate the test file here: https://github.com/allen-cell-animated/simulariumio/pull/52

**Comment by blairlyons** [comment]
test files (same data in JSON and binary): 
https://aics-simularium-data.s3.us-east-2.amazonaws.com/trajectory/test_binary.simularium
https://aics-simularium-data.s3.us-east-2.amazonaws.com/trajectory/test_json.simularium

**Comment by blairlyons** [comment]
code that generated binary https://github.com/simularium/simulariumio/blob/feature/binary/simulariumio/writers/binary_writer.py

**Comment by blairlyons** [comment]
binary format spec https://docs.google.com/document/d/1Hdvw3XieGrTHd7swILzMXLY-dbu-auJVDvt9K1Zbb_Y/edit#heading=h.xk07om75xuhb

**Comment by toloudis** [comment]
Notes:
current format is trajectoryFileInfo json as plaintext, then concatenated binary data, then concatenated plotdata as plaintext json

TBD: how do i know if a given file is binary or not?

1st try: brute-force parse the data and see if there’s some kind of check I can do, but a hint in the trajectory file info json (or possibly a separate file header block) might be a good thing

**Comment by toloudis** [comment]
It's nearly impossible to distinguish a valid binary file from a badly corrupted or invalid json file.  I can sort of do some parsing tricks but they are pretty inefficient and ugly -- basically reading the whole file multiple times.

MIME type is one good way to distinguish text from binary files, but the mime type does not get set when doing drag n drop.  It's something you set at upload time on the server.

There are a couple of different ways to go here but I think the file format has to be changed.  The JSON format should be fine as-is, since it's pure JSON.  

I think the binary version should have some kind of header, and the header needs a few key pieces of info.
Heres how I would think about constructing it.
1. An identifier to say that this is a simularium binary, for example the characters `SIMULARIUMBINARY`.  We can then parse the first few characters to tell if that's the file type.  I recommend making this be some small number of characters but still pretty unique.  `SIMULARIUMBINARY` is exactly 16 characters which is nice.  Even fewer characters might be better but not critical.
2. The total length of this header in bytes (stored as 32-bit integer?)
3. A file format version number as 32bit integer (so if we change the format, parsers can tell which code path to take as early as possible)
--- now begins the real header data which may change with header version
4. A byte offset for the beginning of the first json block (trajectoryfileinfo). or the length of the first json block assuming it immediately follows the header.
5. A byte offset for the beginning of the binary block
6. A byte offset for the beginning of the plotdata json block
7. zero-padding so the entire header is up to some nice power-of-2 number of bytes or similar

I think items 4,5,6 should probably be 64-bit ints but I'm not sure what kind of file sizes we will be dealing with.  So maybe 32bit ints is ok to start with. 
I'm not sure if items 2 and 3 should be swapped in order.
Another way of doing this is having a number of blocks, and then for each block we could store an offset, a length, and a type ascii or binary

**Comment by toloudis** [comment]
example:
```
SIMULARIUMBINARY (16 bytes)
header length (4 bytes)
version 1 (4 bytes)
length of first block (8 bytes)
length of second block (8 bytes)
length of third block (8 bytes)
0-padding (16 bytes)

total = 64 bytes
```

**Comment by toloudis** [comment]
it could even be interesting to have a separate block which contains a list of offsets to the start of each frame of agent data but probably not useful for the current way we read files

**Comment by toloudis** [comment]
if the file size is restricted to less than 4GB, then the block lengths could be stored in the header as 4 byte values, maybe a bit easier to parse

**Comment by blairlyons** [comment]
@toloudis I updated the file format documentation here and added a description of the binary version at the bottom, my proposal based on your comments https://github.com/simularium/simulariumio/blob/feature/binary/file_format.md
- Eric already defined a binary identifier for the spatialData-only binary files streamed from the backend, it's "SIMULARIUMBIN" and then 3 numbers for the version (e.g. "100" for v1.0.0), together it's 16 bytes and I think that would still work? This version would be the binary format version, distinct from the separate versions of the 3 blocks of data within.
- Instead of storing lengths of blocks, can we store the block offsets? Eric was already doing this for each frame within the spatialData, seems like it would also work for the blocks themselves and then it would be consistent with how we handle the frames.
- Do we still need the total length of the header if we have the offset for each of the data blocks?
- We also need to handle the trajectoryInfo and plotData blocks being optional, since the backend is streaming binary with only the spatialData. I'm thinking if we have the offsets for each block that might be enough? But maybe we also need a flag to say whether those blocks are present?

**Comment by toloudis** [comment]
General comment:  I would prefer to keep all values to multiples of 4-byte or 8-byte lengths.  This just enables ease of parsing in multiple different languages, ease of embedding float vs int types, and a bit of predictability/consistency.

> * Eric already defined a binary identifier for the spatialData-only binary files streamed from the backend, it's "SIMULARIUMBIN" and then 3 numbers for the version (e.g. "100" for v1.0.0), together it's 16 bytes and I think that would still work? This version would be the binary format version, distinct from the separate versions of the 3 blocks of data within.

I'm a little unsure about this part.  Wouldn't the "SIMULARIUMBIN" still be the header portion of the second block, so that a spatialData-only file would just be exactly the same as the entire contents of that block? Also, why does this versioning number need major-minor-patch, while most of our other file versions just use a single int that we increment?  Was it supposed to match up to the engine version or something?

> * Instead of storing lengths of blocks, can we store the block offsets? Eric was already doing this for each frame within the spatialData, seems like it would also work for the blocks themselves and then it would be consistent with how we handle the frames.

Block offsets are fine instead of block lengths.  If you are comfortable limiting file size to 4GB then these can be 4 byte integers, otherwise they should be 8-byte integers.

...It also occurs to me that we might want to insert a 4-byte "Block type" as the first 4 bytes of each block. Then we could have interchangeable blocks within the big file and the block type would be a hint about how to parse it. For example we could have one block type that is trajectoryInfo as json, and another block type could be later introduced that is trajectoryInfo as binary.  
Also what if the number of blocks changes? This would imply needing a variable-length section at the end of the header but before the block data.  Number-of-blocks followed by a list of the block offsets. for V1 of this format the number of blocks would always be 3.

> * Do we still need the total length of the header if we have the offset for each of the data blocks?

Having the header length allows us to do sanity checks against version number, and against the first offset, in case we have to modify the header later and change its size.  Yes it's extra data but it doesn't really hurt.  

> * We also need to handle the trajectoryInfo and plotData blocks being optional, since the backend is streaming binary with only the spatialData. I'm thinking if we have the offsets for each block that might be enough? But maybe we also need a flag to say whether those blocks are present?

The variable-length number of blocks (and each block having a blocktype) that I mention above would handle this.  Then the header might potentially only have one single block offset.  Alternatively, can we just have those blocks always be present but contain some form of empty data?

**Comment by blairlyons** [comment]
> Wouldn't the "SIMULARIUMBIN" still be the header portion of the second block, so that a spatialData-only file would just be exactly the same as the entire contents of that block? 

Wouldn't it make more sense in the long run to have only one binary header? We would have to parse the different header just for version 1, i.e. "SIMULARIUMBIN100" instead of "SIMULARIUMBINARY"+int, but we could deprecate it soon?

> why does this versioning number need major-minor-patch, while most of our other file versions just use a single int that we increment?

I don't think it does, it's just for historical reasons, we didn't coordinate.

> we might want to insert a 4-byte "Block type" as the first 4 bytes of each block.

This sounds great, I like the idea of the blocks being more modular so we can add and remove them later, and it seems like a good way to handle the optional and heterogeneous JSON/binary data types.

I updated the spec at the bottom here https://github.com/simularium/simulariumio/blob/feature/binary/file_format.md

**Comment by toloudis** [comment]
When the engine sends data, it completely splits the trajectoryfileinfo from the binary agent data. In fact it caches the data as two separate files, currently.  (I would be interested in a caching approach that splits up the agentdata into frames also.) The binary agent data gets sent in websocket messages that begin with SIMULARIUMBIN.  I'm not against changing it but it would require engine changes as well.  

Does the simularium-engine need to know about the new binary format?  I suppose it does... in that case I am all in favor of removing SIMULARIUMBIN from the agentdata block and just having it be the overall file header. 

One thing occurred to me: maybe a block should also know its own length. That way if you need to parse JSON you can just grab all of it without having to check for the end or remember the offset of the next block.  This is a good reason to either encode both offsets and block lengths in the header, or to stick the block length right after the block type for each block.

Also in the spec we should say that json must be utf-8 encoded when it's in a block. (I'm not sure if json is utf-8 by definition)

This extensible number of blocks is going to make the format very flexible.  I have to ask one more time: is 4GB really a reasonable limit for these files? (4 byte offsets and lengths?)  Any idea what a "large" number of agents and a "large" number of times would be?

**Comment by toloudis** [comment]
Notes, simplified:
* table of contents should list block offset and block length for each block.
* each block should have a block type and block length as its header
* we are maxing out at 4GB per file so that offsets and lengths can be 4 bytes.  this needs to be enforced at write time.
* I'm not 100% sold that we need to put block types in the table of contents but this could be a convenience thing
* is the THEFRAMEENDSHERE necessary anymore? I think not. (and if so could the engine be the one to add it as part of websocket transmission)

**Comment by blairlyons** [comment]
ok, updated version is here https://github.com/simularium/simulariumio/blob/feature/binary/file_format.md

Like we talked about in dev meeting, I think it's reasonable to limit files to 4GB and larger trajectories would be split between multiple files. As long as we require data for each timestep to be in one file, not split between two. And then we don't need the EOF signal since the frame length will be provided.

I'll start implementing these updates, lmk if you think of anything else.

**Comment by blairlyons** [comment]
@toloudis I updated the test data (same data in JSON and binary):
https://aics-simularium-data.s3.us-east-2.amazonaws.com/trajectory/test_json.simularium
https://aics-simularium-data.s3.us-east-2.amazonaws.com/trajectory/test_binary.simularium

**Comment by toloudis** [comment]
Can I request one small change?  In the header table of contents, instead of a separate array of block lengths, block offsets, and block types, can we do an array of [block offset, block length, block type]?  just transpose it?  I feel like that is the more likely access pattern, where I would want to get all 3 pieces of info for each block.

**Comment by blairlyons** [comment]
@toloudis done, data is updated at the same urls

**Comment by toloudis** [comment]
@blairlyons I dropped some comments in https://github.com/simularium/simulariumio/pull/60 with a couple of bugs that require the files to be regenerated.
