### ISSUE TITLE
No warning for default display type

### ISSUE THREAD

**Issue by blairlyons** [simularium/simularium-viewer#210]
## Use Case
It would be nice if the "No DisplayType. Geometry will default to spheres" warning did not pop up as an error for the user.

## Acceptance Criteria
An agent without display type does not trigger any warnings/errors, at least not that pop up for the user.

## Details
It's not necessary to warn users that the default display type was used, SimulariumIO only adds display type if something non-default was specified.

It would be ok to add a log to the console instead.

![Screen Shot 2021-10-18 at 3 59 47 PM](https://user-images.githubusercontent.com/12102071/137821742-9b796ba5-2eaf-4922-865c-359054fa0a73.png)

**Comment by meganrm** [comment]
I thought simulariumio actually set the displayType to "Sphere" if none was given, is that not true? I was mostly expecting this to always be set

**Comment by meganrm** [comment]
Ok thanks. Yeah, I do think it would be good to still give a warning if they do provide a url or a display type that is not a sphere, and it gets defaulted to sphere, just so they know why it looks different than they expected. I don't think I've written up an issue yet, but longer term, I think it's a good idea to modify the error response to send a level, like, error, warning, info. So that the front end can be more nuanced for things like this. If you agree Blair, I can write up the ticket for the viewer, and a question UX ticket for the front end on how to display them
